version: '3'

services:
  postgresql:
    container_name: postgresql
    image: postgres:12.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./init:/docker-entrypoint-initdb.d/

  app:
    container_name: spring-boot-app
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
    - "DB_HOST=postgresql"
    - "POSTGRES_USER=postgres"
    - "POSTGRES_PASSWORD=postgres"
    - "SERVER_PORT=8080"
    expose:
      - "8080"
    depends_on:
      - postgresql
    restart: always

