version: '3'

services:
  postgresql:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  app:
    container_name: spring-boot-app
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
    - "DB_HOST=postgres"
    - "POSTGRES_USER=postgres"
    - "POSTGRES_PASSWORD=postgres"
    - "SERVER_PORT=8080"
    expose:
      - "8080"
    depends_on:
      - postgresql
